force-app/main/default/objects/TriggerUnitTest__c/TriggerUnitTest__c.object-meta.xml
<CustomObject>
    <label>TriggerUnitTest</label>
    <nameField>
        <displayFormat>TUT-{0000}</displayFormat>
        <label>TriggerUnitTest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TriggerUnitTests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TriggerUnitTest__c/fields/BeforeCheck__c.field-meta.xml
<CustomField>
    <fullName>BeforeCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BeforeCheck</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TriggerHandlerTest.cls
@isTest
public class TriggerHandlerTest {
    static testMethod void afterAndBeforeInsert() {
		TriggerUnitTest__c uTest = new TriggerUnitTest__c();
        
        Test.startTest();
        INSERT uTest;
        Test.stopTest();
        
        List<TriggerUnitTest__c> records = [Select Id From TriggerUnitTest__c WHERE BeforeCheck__c = true];
        system.assertEquals(2, records.size());
    }
    
    static testMethod void afterAndBeforeUpdate() {
		TriggerUnitTest__c uTest = new TriggerUnitTest__c();
        INSERT uTest; 
        
        Test.startTest();
		UPDATE uTest;
        Test.stopTest();
        
        List<TriggerUnitTest__c> records = [Select Id From TriggerUnitTest__c];
        system.assertEquals(2, records.size());
    }
    
    static testMethod void afterAndBeforeDelete() {
		TriggerUnitTest__c uTest = new TriggerUnitTest__c();
        INSERT uTest;
        
        Test.startTest();
        DELETE uTest;
        Test.stopTest();
        
        List<TriggerUnitTest__c> records = [Select Id From TriggerUnitTest__c];
        system.assertEquals(1, records.size());
    }
    
    static testMethod void afterAndBeforeUndelete() {
		TriggerUnitTest__c uTest = new TriggerUnitTest__c();
        INSERT uTest;
        DELETE uTest;
        
        Test.startTest();
		UNDELETE uTest;
        Test.stopTest();
        
        List<TriggerUnitTest__c> records = [Select Id From TriggerUnitTest__c];
        system.assertEquals(2, records.size());
    }
}