force-app/main/default/objects/TriggerUnitTest__c/TriggerUnitTest__c.object-meta.xml
<CustomObject>
    <label>TriggerUnitTest</label>
    <nameField>
        <displayFormat>TUT-{0000}</displayFormat>
        <label>TriggerUnitTest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TriggerUnitTests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TriggerUnitTest__c/fields/BeforeCheck__c.field-meta.xml
<CustomField>
    <fullName>BeforeCheck__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BeforeCheck</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TriggerUnitTestBefore.cls
public class TriggerUnitTestBefore extends Process {
      public override IProcess run() {
            //call business logic here
            setBefore();
          
            system.debug(event); //--> String result: beforeInsert
      
            return this;
      }

      private void setBefore() {
            //holds before records in a List
            List<TriggerUnitTest__c> objList = (List<TriggerUnitTest__c>) oldList;
                  
            //holds before records in a map
            Map<Id, TriggerUnitTest__c> objMap = (Map<Id, TriggerUnitTest__c>) oldMap;
                  
            //sets records in before context to be avaliable in new context
            for(TriggerUnitTest__c record : (List<TriggerUnitTest__c>) newList) {
                              record.BeforeCheck__c = true;
            }
      }
}