force-app/main/default/objects/TriggerDefinition__mdt/TriggerDefinition__mdt.object-meta.xml
<CustomObject>
    <label>Trigger Definition</label>
    <pluralLabel>Trigger Definitions</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggerDefinition__mdt/fields/acceptReentrancy__c.field-meta.xml
<CustomField>
    <fullName>acceptReentrancy__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If checkbox is active, this trigger can be executed multiple times in a single transaction.</inlineHelpText>
    <label>Accept reentrancy</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerDefinition__mdt/fields/ApexClassName__c.field-meta.xml
<CustomField>
    <fullName>ApexClassName__c</fullName>
    <inlineHelpText>Put the name of the apex class here, which implements the trigger framework.</inlineHelpText>
    <label>Apex Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TriggerDefinition__mdt/fields/Context__c.field-meta.xml
<CustomField>
    <fullName>Context__c</fullName>
    <label>Context</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>before</fullName>
                <default>true</default>
                <label>before</label>
            </value>
            <value>
                <fullName>after</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TriggerDefinition__mdt/fields/isDelete__c.field-meta.xml
<CustomField>
    <fullName>isDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerDefinition__mdt/fields/isInsert__c.field-meta.xml
<CustomField>
    <fullName>isInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerDefinition__mdt/fields/isUndelete__c.field-meta.xml
<CustomField>
    <fullName>isUndelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Undelete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerDefinition__mdt/fields/isUpdate__c.field-meta.xml
<CustomField>
    <fullName>isUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TriggerDefinition__mdt/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <inlineHelpText>Put the name of the sObject here, which fires the trigger.</inlineHelpText>
    <label>Object Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TriggerDefinition__mdt/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <inlineHelpText>All triggers are executed in a ascending order by this number for this object.</inlineHelpText>
    <label>Order Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TriggerQuery.cls
public class TriggerQuery {
      public List<TriggerDefinition__mdt> getTrigger(String sObjectType, String eventName) {
            List<TriggerDefinition__mdt> triggers;
            String filter;
            if(String.isNotBlank(eventname)) {
                  if(eventName.containsIgnoreCase('before')) {
                        if(eventName.containsIgnoreCase('insert')) {
                              filter = 'Context__c = \'before\' AND isInsert__c = true';
                        } else if(eventName.containsIgnoreCase('update')) {
                              filter = 'Context__c = \'before\' AND isUpdate__c = true';
                        } else if(eventName.containsIgnoreCase('delete')) {
                              filter = 'Context__c = \'before\' AND isDelete__c = true';
                        }
                  } else if(eventName.containsIgnoreCase('after')) {
                        if(eventName.containsIgnoreCase('insert')) {
                              filter = 'Context__c = \'after\' AND isInsert__c = true';
                        } else if(eventName.containsIgnoreCase('update')) {
                              filter = 'Context__c = \'after\' AND isUpdate__c = true';
                        } else if(eventName.containsIgnoreCase('undelete')) {
                              filter = 'Context__c = \'after\' AND isUndelete__c = true';
                        } else if(eventName.containsIgnoreCase('delete')) {
                              filter = 'Context__c = \'after\' AND isDelete__c = true';
                        }
                  }

                  String orderBy = ' ORDER BY Order_Number__c ASC';
                  String query = 'Select Id, ApexClassName__c, acceptReentrancy__c FROM TriggerDefinition__mdt WHERE isActive__c = true AND ObjectName__c = :sObjectType AND ' + filter + orderBy;

                  try {
                        triggers = (List<TriggerDefinition__mdt>) Database.query(query);
                  } catch (Exception e) {
                        System.debug('Trigger not found: ' + sObjectType);
                  }
            }

            return triggers;
      }
}